"""Detect model-fallback events in Claude Code session transcripts.

Claude Fable 5 (driving the evolution loop from 2026-06-09) ships with
safety classifiers that fall back to Claude Opus 4.8 on sensitive topics.
Each assistant message in a Claude Code transcript JSONL records the model
that actually served the response, so a fallback shows up as claude-opus-*
messages inside an otherwise claude-fable-* session file.

Why it matters: article frontmatter records ``ai_system`` and the citation
convention maps it to an AI pseudonym (Fabcinq, C. vs Oquatre-huit, C. —
see expand-topic SKILL.md §5.5). A silent fallback mid-fork means text
attributed to Fable was generated by Opus; detection lets a human annotate
the affected article rather than mis-attributing it.

Detection is client-side best-effort: if the API ever reports the fallback
response as still being claude-fable-*, nothing here can see it. Transcript
evidence (mixed opus-4-7/opus-4-8 sessions on upgrade days) shows the field
tracks the serving model per response, so the signal is expected to work.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LOG_DIR = REPO_ROOT.parent / "unfinishablemap_log"
STATE_PATH = LOG_DIR / "model-fallback-state.json"
TODO_PATH = REPO_ROOT / "obsidian" / "workflow" / "todo.md"

# Model families that never indicate a fallback when they appear alongside
# the primary model: haiku serves background work (title generation, cheap
# subagents) by design, and "<synthetic>" is Claude Code's placeholder model
# on synthetic error messages.
IGNORED_MODEL_PREFIXES = ("claude-haiku", "<")

# Prefix of the model expected to drive the loop. Fallback severity applies
# only when the dominant model of a transcript matches this prefix.
PRIMARY_PREFIX = "claude-fable"

FIRST_RUN_LOOKBACK_HOURS = 24
RESCAN_OVERLAP_MINUTES = 10


@dataclass
class FallbackEvent:
    """One transcript file containing same-file model mixing."""

    transcript: Path
    dominant: str
    foreign_counts: dict[str, int]
    first_foreign_ts: str
    last_foreign_ts: str
    new_foreign_count: int
    severity: str  # "FALLBACK-SUSPECTED" | "MIXED-MODELS"


def _normalize_model(model: str) -> str:
    """Strip variant decorations that don't change identity for attribution.

    claude-fable-5[1m]        → claude-fable-5   (context-window designator)
    claude-opus-4-5-20251101  → claude-opus-4-5  (dated snapshot)

    Version bumps within a family (opus-4-7 vs opus-4-8) are NOT collapsed:
    they map to different pseudonyms, so same-file mixing is reportable.
    """
    model = re.sub(r"\[[^\]]*\]$", "", model)
    model = re.sub(r"-20\d{6}$", "", model)
    return model


def transcript_dir(repo_root: Path = REPO_ROOT) -> Path:
    """Claude Code project transcript directory for this repo."""
    mangled = str(repo_root).replace("/", "-").replace(".", "-").replace("_", "-")
    return Path.home() / ".claude" / "projects" / mangled


def _load_last_scan() -> datetime | None:
    if not STATE_PATH.exists():
        return None
    try:
        raw = json.loads(STATE_PATH.read_text())
        return datetime.fromisoformat(raw["last_scan"])
    except (ValueError, KeyError, json.JSONDecodeError):
        return None


def _save_last_scan(when: datetime) -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps({"last_scan": when.isoformat()}) + "\n")


def _parse_ts(raw: str) -> datetime:
    return datetime.fromisoformat(raw.replace("Z", "+00:00"))


def _assistant_messages(path: Path) -> list[tuple[str, datetime]]:
    """Extract (model, timestamp) for each assistant message in a transcript."""
    out: list[tuple[str, datetime]] = []
    try:
        with path.open() as fh:
            for line in fh:
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if entry.get("type") != "assistant":
                    continue
                model = (entry.get("message") or {}).get("model")
                ts_raw = entry.get("timestamp")
                if not model or not ts_raw:
                    continue
                try:
                    out.append((model, _parse_ts(ts_raw)))
                except ValueError:
                    continue
    except OSError:
        pass
    return out


def scan_transcripts(
    since: datetime,
    root: Path | None = None,
) -> list[FallbackEvent]:
    """Scan transcripts modified after ``since`` for same-file model mixing.

    Only events with at least one foreign message newer than ``since`` are
    returned, so already-reported mixing is not re-raised on later runs.
    """
    root = root or transcript_dir()
    if not root.is_dir():
        return []

    overlap = since - timedelta(minutes=RESCAN_OVERLAP_MINUTES)
    events: list[FallbackEvent] = []

    for path in sorted(root.rglob("*.jsonl")):
        try:
            mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
        except OSError:
            continue
        if mtime < overlap:
            continue

        messages = [
            (_normalize_model(m), t)
            for m, t in _assistant_messages(path)
            if not m.startswith(IGNORED_MODEL_PREFIXES)
        ]
        if not messages:
            continue

        counts = Counter(m for m, _ in messages)
        dominant = counts.most_common(1)[0][0]
        primary_present = any(m.startswith(PRIMARY_PREFIX) for m in counts)

        # Foreign = non-primary when the primary model appears at all. A stuck
        # fallback session (begins on fable, runs opus for the rest of its
        # life) is dominant-opus, so keying "foreign" off the dominant model
        # would invert the report and downgrade the severity. Confirmed
        # 2026-06-10/11: a loop session ran 5x fable then 1276x opus over
        # ~34h — fable + anything-else in one file is always suspect.
        if primary_present:
            foreign = [(m, t) for m, t in messages if not m.startswith(PRIMARY_PREFIX)]
            severity = "FALLBACK-SUSPECTED"
        else:
            foreign = [(m, t) for m, t in messages if m != dominant]
            severity = "MIXED-MODELS"
        if not foreign:
            continue

        new_foreign = [t for _, t in foreign if t > since]
        if not new_foreign:
            continue
        events.append(
            FallbackEvent(
                transcript=path,
                dominant=dominant,
                foreign_counts=dict(Counter(m for m, _ in foreign)),
                first_foreign_ts=min(t for _, t in foreign).isoformat(),
                last_foreign_ts=max(t for _, t in foreign).isoformat(),
                new_foreign_count=len(new_foreign),
                severity=severity,
            )
        )

    return events


def queue_attribution_task(event: FallbackEvent, today: str) -> bool:
    """Append a P2 attribution-check task to todo.md for one fallback event.

    Returns False (no write) when todo.md already references the transcript,
    so repeated runs do not stack duplicate tasks.
    """
    todo = TODO_PATH.read_text()
    stem = event.transcript.stem
    if stem in todo:
        return False

    foreign_desc = ", ".join(f"{n}x {m}" for m, n in sorted(event.foreign_counts.items()))
    stuck = not event.dominant.startswith(PRIMARY_PREFIX)
    if stuck:
        scope = (
            f"Dominant model is the fallback ({event.dominant}) — SESSION-LEVEL STICK: the "
            f"session began on the primary model and ran the fallback for the rest of its "
            f"life. Treat EVERYTHING the loop wrote in the window as fallback-generated "
            f"(bulk annotation; cross-reference every changelog entry in the window), not "
            f"a brief excursion. "
        )
    else:
        scope = ""
    block = (
        f"### P2: Verify ai_system attribution after model-fallback event ({today})\n"
        f"- **Type**: refine-draft\n"
        f"- **Notes**: Transcript {stem}.jsonl shows {foreign_desc} message(s) alongside the "
        f"primary model between {event.first_foreign_ts} and "
        f"{event.last_foreign_ts} (UTC). {scope}Cross-reference workflow/changelog.md for "
        f"the task(s) running in that window. If a content-writing fork was affected, "
        f'annotate the article\'s ai_system (e.g. "claude-fable-5+claude-opus-4-8") and use '
        f"the matching pseudonym for self-citations (expand-topic SKILL.md §5.5). If the "
        f"window covers only non-content work (reviews, queue maintenance), close as "
        f"no-op.\n"
        f"- **Source**: check-model-fallback\n"
        f"- **Generated**: {today}\n"
    )

    marker = "## Active Tasks\n"
    idx = todo.find(marker)
    if idx == -1:
        return False
    insert_at = idx + len(marker)
    TODO_PATH.write_text(todo[:insert_at] + "\n" + block + todo[insert_at:])
    return True


def run(queue_tasks: bool = False, since_hours: float | None = None) -> list[FallbackEvent]:
    """Scan, report to stdout, persist scan marker, optionally queue tasks."""
    now = datetime.now(timezone.utc)
    if since_hours is not None:
        since = now - timedelta(hours=since_hours)
    else:
        since = _load_last_scan() or now - timedelta(hours=FIRST_RUN_LOOKBACK_HOURS)

    events = scan_transcripts(since)
    today = now.date().isoformat()

    if not events:
        print(f"[OK] No model-fallback events since {since.isoformat()}")
    for event in events:
        foreign_desc = ", ".join(
            f"{n}x {m}" for m, n in sorted(event.foreign_counts.items())
        )
        print(
            f"[{event.severity}] {event.transcript.name}: dominant={event.dominant}, "
            f"foreign={foreign_desc}, window={event.first_foreign_ts}.."
            f"{event.last_foreign_ts}"
        )
        if queue_tasks and event.severity == "FALLBACK-SUSPECTED":
            if queue_attribution_task(event, today):
                print(f"[QUEUED] P2 attribution task for {event.transcript.stem}")
            else:
                print(f"[SKIP] todo.md already references {event.transcript.stem}")

    _save_last_scan(now)
    return events
